version: "3"
services:
  paytaca-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: paytaca-app
    hostname: paytaca-app
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
    - '8100:8080'
    command: /bin/sh -c "npx quasar dev"
    volumes:
      - ".:/app/"
      - "paytaca_app__node_modules:/app/node_modules"

volumes:
  paytaca_app__node_modules:
    driver: 'local'
